spring:
  application:
    name: ecommerce-backend

  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      database: ${MONGODB_DATABASE:ecommerce_db}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.example.ecommercebackend: DEBUG

mock:
  payment:
    delay-ms: ${MOCK_PAYMENT_DELAY_MS:3000}
    success-rate: ${MOCK_PAYMENT_SUCCESS_RATE:0.8}
